In [1]:
import pandas as pd

df = pd.read_excel("../data/cleandata.xlsx")

df.head()

                 date  Power Consumption  Outdoor Temperature  Occupancy
0 2018-05-22 00:00:00              71.98                15.72          1
1 2018-05-22 00:15:00              71.00                15.37          1
2 2018-05-22 00:30:00              65.20                15.27          0
3 2018-05-22 00:45:00              95.90                16.03          0
4 2018-05-22 01:00:00              43.60                15.28          0

In [3]:
df["Power_Norm"] = (
    df["Power Consumption"]
    - df["Power Consumption"].min()
) / (
    df["Power Consumption"].max()
    - df["Power Consumption"].min()
)

df["Occupancy_Norm"] = (
    df["Occupancy"]
    - df["Occupancy"].min()
) / (
    df["Occupancy"].max()
    - df["Occupancy"].min()
)

df["Temperature_Norm"] = (
    df["Outdoor Temperature"]
    - df["Outdoor Temperature"].min()
) / (
    df["Outdoor Temperature"].max()
    - df["Outdoor Temperature"].min()
)

In [5]:
df["Power_State"] = (
    (df["Power_Norm"] * 10)
    .round()
    / 10
)

df["Occupancy_State"] = (
    (df["Occupancy_Norm"] * 10)
    .round()
    / 10
)

df["Temperature_State"] = (
    (df["Temperature_Norm"] * 10)
    .round()
    / 10
)

In [7]:
df[[
    "Power_State",
    "Occupancy_State",
    "Temperature_State"
]].head(20)

    Power_State  Occupancy_State  Temperature_State
0           0.4              0.0                0.4
1           0.4              0.0                0.4
2           0.3              0.0                0.4
3           0.5              0.0                0.4
4           0.2              0.0                0.4
5           0.2              0.0                0.4
6           0.3              0.0                0.4
7           0.4              0.0                0.3
8           0.2              0.0                0.3
9           0.2              0.0                0.3
10          0.2              0.0                0.3
11          0.1              0.0                0.3
12          0.1              0.0                0.2
13          0.2              0.0                0.2
14          0.2              0.0                0.2
15          0.1              0.0                0.2
16          0.2              0.0                0.2
17          0.3              0.0                0.2
18          0.4              0.0                0.2
19          0.3              0.0                0.2

In [9]:
df["State_ID"] = (
    df["Power_State"].astype(str)
    + "-"
    + df["Occupancy_State"].astype(str)
    + "-"
    + df["Temperature_State"].astype(str)
)

In [10]:
print(
    "Unique States:",
    df["State_ID"].nunique()
)

Unique States: 337